package com.tradeintel.ai.controller;

import com.tradeintel.ai.model.Stock;
import com.tradeintel.ai.model.TradeSignal;
import com.tradeintel.ai.model.TradingStrategy;
import com.tradeintel.ai.service.TradingStrategyService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * REST controller for trading strategy management
 */
@RestController
@RequestMapping("/api/strategies")
@RequiredArgsConstructor
@Slf4j
public class TradingStrategyController {

    private final TradingStrategyService strategyService;

    /**
     * Get all strategies
     */
    @GetMapping
    public ResponseEntity<List<TradingStrategy>> getAllStrategies() {
        try {
            List<TradingStrategy> strategies = strategyService.getAllStrategies();
            return ResponseEntity.ok(strategies);
        } catch (Exception e) {
            log.error("Error fetching strategies", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Get active strategies only
     */
    @GetMapping("/active")
    public ResponseEntity<List<TradingStrategy>> getActiveStrategies() {
        try {
            List<TradingStrategy> strategies = strategyService.getActiveStrategies();
            return ResponseEntity.ok(strategies);
        } catch (Exception e) {
            log.error("Error fetching active strategies", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Get strategy by ID
     */
    @GetMapping("/{id}")
    public ResponseEntity<TradingStrategy> getStrategy(@PathVariable Long id) {
        try {
            return strategyService.getStrategyById(id)
                    .map(ResponseEntity::ok)
                    .orElse(ResponseEntity.notFound().build());
        } catch (Exception e) {
            log.error("Error fetching strategy {}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Create a new strategy
     */
    @PostMapping
    public ResponseEntity<?> createStrategy(@RequestBody TradingStrategy strategy) {
        try {
            TradingStrategy created = strategyService.createStrategy(strategy);
            return ResponseEntity.status(HttpStatus.CREATED).body(created);
        } catch (Exception e) {
            log.error("Error creating strategy", e);
            Map<String, String> error = new HashMap<>();
            error.put("error", e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error);
        }
    }

    /**
     * Update an existing strategy
     */
    @PutMapping("/{id}")
    public ResponseEntity<?> updateStrategy(@PathVariable Long id, @RequestBody TradingStrategy strategy) {
        try {
            TradingStrategy updated = strategyService.updateStrategy(id, strategy);
            return ResponseEntity.ok(updated);
        } catch (IllegalArgumentException e) {
            Map<String, String> error = new HashMap<>();
            error.put("error", e.getMessage());
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(error);
        } catch (Exception e) {
            log.error("Error updating strategy {}", id, e);
            Map<String, String> error = new HashMap<>();
            error.put("error", e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error);
        }
    }

    /**
     * Delete a strategy
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteStrategy(@PathVariable Long id) {
        try {
            strategyService.deleteStrategy(id);
            Map<String, String> response = new HashMap<>();
            response.put("message", "Strategy deleted successfully");
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            log.error("Error deleting strategy {}", id, e);
            Map<String, String> error = new HashMap<>();
            error.put("error", e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(error);
        }
    }

    /**
     * Get signals generated by a strategy
     */
    @GetMapping("/{id}/signals")
    public ResponseEntity<?> getStrategySignals(@PathVariable Long id,
            @RequestParam(defaultValue = "10") int limit) {
        try {
            List<TradeSignal> signals = strategyService.getRecentSignalsForStrategy(id, limit);
            return ResponseEntity.ok(signals);
        } catch (Exception e) {
            log.error("Error fetching signals for strategy {}", id, e);
            Map<String, String> error = new HashMap<>();
            error.put("error", e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(error);
        }
    }

    /**
     * Get available strategy implementations
     */
    @GetMapping("/implementations")
    public ResponseEntity<?> getStrategyImplementations() {
        Map<String, String> implementations = new HashMap<>();
        implementations.put("RSIStrategy", "RSI-based momentum strategy");
        implementations.put("MACDStrategy", "MACD crossover strategy");
        implementations.put("movingAverageCrossoverStrategy", "Moving Average crossover (Golden/Death Cross)");
        implementations.put("bollingerBandsStrategy", "Bollinger Bands mean reversion strategy");

        return ResponseEntity.ok(implementations);
    }
}
